Exp:
  out_dir: "output/MemAE/rsna/"
  gpu: 6

Model:
  network: "MemAE"  # AE, AE-U, MemAE
  mp: 1  # multiplier that controls the capacity of AE
  ls: 16  # the output size of encoder
  mem_dim: 25
  shrink_thres: 0.0
  entropy_loss_weight: 0.0002
  layer: 4

Data:
  dataset: "rsna"  # rsna, vin
  img_size: 64

Solver:
  bs: 64
  lr: 5.0e-4
  weight_decay: 0
  num_epoch: 250
  seed: 7
  Lambda: 1

