Exp:
  out_dir: "output/AEU/Vin/"
  gpu: 2

Model:
  network: "AE-U"  # AE, AE-U, MemAE
  mp: 1  # multiplier that controls the capacity of AE
  ls: 16  # the output size of encoder
  mem_dim: Null
  shrink_thres: Null
  layer: 4

Data:
  dataset: "vin"  # rsna, vin
  img_size: 64

Solver:
  bs: 64
  lr: 1.0e-3
  weight_decay: 0
  num_epoch: 250
  seed: 9
  Lambda: 1

